config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'reports#index'
    resource 'reports'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/powerbi.rb
module Powerbi
	extend ActiveSupport::Concern
	class Api
		BASE_URL   = "https://login.microsoftonline.com"
    	RESOURCE   = "https://analysis.windows.net/powerbi/api"

		def initialize
			@tenantId  = CONFIG['tenant_id']
			@base_api_url = 'https://api.powerbi.com/v1.0/myorg'
		end

		def authenticate
			begin
				authenticate_url = "#{BASE_URL}/#{@tenantId}/oauth2/token"
				response = Excon.post(authenticate_url,:body => build_body,:headers => build_headers)
				body = JSON.parse(response.body)["access_token"]
			rescue StandardError => e
				Rails.logger.info "Rescued: #{e.inspect}"
			end
		end


		def embed_token(datasets,report_id,workspace_id,access_token)	
			embed_token_url = "#{@base_api_url}/groups/#{workspace_id}/reports/#{report_id}/GenerateToken"
			response = Excon.post(embed_token_url,:body => JSON.generate(build_body_embed_token(datasets)),:headers =>build_headers_reports(access_token))
	        response = JSON.parse(response.body)["token"]
	    end

		def reports(workspace_id,access_token)
        	response = Excon.get("#{@base_api_url}/groups/#{workspace_id}/reports",:headers =>build_headers_reports(access_token))
	        response = JSON.parse(response.body)["value"]
	    end


		def report(report_id,workspace_id,access_token)
			response = Excon.get("#{@base_api_url}/groups/#{workspace_id}/reports/#{report_id}",:headers =>build_headers_reports(access_token))
	      	response = eval(response.data[:body])
		end

		private

	    def build_body
	      URI.encode_www_form({
	        client_id: CONFIG['client_id'],
	        client_secret:  CONFIG['client_secret'],
	        grant_type: 'client_credentials',
	        resource: RESOURCE,
	      })
	    end

	    def build_headers
	      { 'Content-Type' => 'application/x-www-form-urlencoded'}
	    end

	    def build_headers_reports(access_token)
            { 
            	'Content-Type' => 'application/json',
                'Authorization' => "Bearer #{access_token}"
            }
                    
	    end

    	def build_body_embed_token(datasets)
	    	{
            'access_level' => "view",
            'identities' => [
                {
                   'username' =>  Rails.configuration.ObjectId,
					'customData' => "Rajalakshmi",
					'roles' => ["ReadOnly"],
                    'datasets' => [ datasets]
                }
            ]}
	    end

	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	include Powerbi

	def  index
		@access_token = Powerbi::Api.new.authenticate
		@reports = Powerbi::Api.new.reports(CONFIG['workspace_id'],@access_token)
	end

	def show
		datasets = params['datasets']
		report_id = params['id']
		@access_token = Powerbi::Api.new.authenticate
		@embed_token = Powerbi::Api.new.embed_token(datasets,report_id,CONFIG['workspace_id'],@access_token)
		@report = Powerbi::Api.new.report(report_id,CONFIG['workspace_id'],@access_token)
	end

	private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/index.html.erb
Power BI - Report Listing



<ul>
<% @reports.each do |report| -%>
<li><%= link_to "Report #{report['name']}", reports_path(:id=>report['id'],:datasets=>report['datasetId'])%></li>
<%end -%>
</ul>
<div id = "reportContainer"></div>

<script type="text/javascript">

$(document).ready(function() {
  // generate_report();
});
</script>

app/views/reports/show.html.erb
Report







<input type="hidden" value="<%= @embed_token%>" id="accessToken" />
<input type="hidden" value="<%= @report[:embedUrl]%>" id="embedURL" />
<input type="hidden" value="<%= @report[:id]%>" id="reportId" />



<div id = "reportContainer"></div>
<script type="text/javascript">

$(document).ready(function() {
  generate_report();
});
</script>